load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "elastic_text_fiddle",
    srcs = ["elastic_text_fiddle.cc"],
    hdrs = ["elastic_text_fiddle.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//:fiddle_base",
        "//graphics:webgl_canvas_context",
        "//text:font_cycle",
        "//text:skia_font_manager",
        "//utils:random_permutation",
        "@skia//:core",
        "@skia//:skparagraph_harfbuzz_skunicode",
        "@skia//:skunicode_icu",
    ],
)

cc_library(
    name = "sksl_image_proc_fiddle",
    srcs = ["sksl_image_proc_fiddle.cc"],
    hdrs = ["sksl_image_proc_fiddle.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//:fiddle_base",
        "//graphics:webgl_canvas_context",
        "//images:skia_image_store",
        "//text:skia_font_manager",
        "@skia//:core",
    ],
)

cc_library(
    name = "shape_intersection_fiddle",
    srcs = ["shape_intersection_fiddle.cc"],
    hdrs = ["shape_intersection_fiddle.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//:fiddle_base",
        "//graphics:webgl_canvas_context",
        "//text:skia_font_manager",
        "@skia//:core",
        "@skia//:pathops",
    ],
)

cc_library(
    name = "ribbon_field_fiddle",
    srcs = ["ribbon_field_fiddle.cc"],
    hdrs = ["ribbon_field_fiddle.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//:fiddle_base",
        "//graphics:webgl_canvas_context",
        "//text:font_cycle",
        "//text:skia_font_manager",
        "//utils:color_utils",
        "@skia//:core",
        "@skia//:pathops",
        "@skia//:skparagraph_harfbuzz_skunicode",
        "@skia//:skunicode_icu",
    ],
)

cc_library(
    name = "skia_pulse_benchmark",
    srcs = ["skia_pulse_benchmark.cc"],
    hdrs = ["skia_pulse_benchmark.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

cc_library(
    name = "skia_drawing_builder",
    srcs = ["skia_drawing_builder.cc"],
    hdrs = ["skia_drawing_builder.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//utils:color_utils",
        "@skia//:core",
    ],
)

cc_library(
    name = "skia_webgl_fiddle",
    srcs = ["skia_webgl_fiddle.cc"],
    hdrs = ["skia_webgl_fiddle.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":skia_drawing_builder",
        ":skia_pulse_benchmark",
        "//:fiddle_base",
        "//graphics:webgl_canvas_context",
        "@skia//:core",
    ],
)

cc_library(
    name = "skia_cpu_fiddle",
    srcs = ["skia_cpu_fiddle.cc"],
    hdrs = ["skia_cpu_fiddle.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":skia_drawing_builder",
        ":skia_pulse_benchmark",
        "//:fiddle_base",
        "//graphics:raster_canvas_context",
        "@skia//:core",
    ],
)
