load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "skia_image_store",
    srcs = ["skia_image_store.cc"],
    hdrs = ["skia_image_store.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "@skia//:core",
        "@skia//:jpeg_decode_codec",
    ],
)
