load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bicubic_bezier_patch",
    srcs = ["bicubic_bezier_patch.cc"],
    hdrs = ["bicubic_bezier_patch.h"],
    deps = ["@skia//:core"],
)

cc_test(
    name = "bicubic_bezier_patch_test",
    srcs = ["bicubic_bezier_patch_test.cc"],
    deps = [
        ":bicubic_bezier_patch",
        "@skia//:core",
    ],
)

cc_library(
    name = "catmull_rom_spline",
    srcs = ["catmull_rom_spline.cc"],
    hdrs = ["catmull_rom_spline.h"],
    deps = ["@skia//:core"],
)

cc_test(
    name = "catmull_rom_spline_test",
    srcs = ["catmull_rom_spline_test.cc"],
    deps = [
        ":catmull_rom_spline",
        "@skia//:core",
    ],
)

cc_library(
    name = "contour_regions",
    srcs = ["contour_regions.cc"],
    hdrs = ["contour_regions.h"],
    deps = [
        ":catmull_rom_spline",
        ":marching_squares",
        "@skia//:core",
        "@skia//:pathops",
    ],
)

cc_test(
    name = "contour_regions_test",
    srcs = ["contour_regions_test.cc"],
    deps = [
        ":contour_regions",
        "@skia//:core",
    ],
)

cc_library(
    name = "marching_squares",
    srcs = ["marching_squares.cc"],
    hdrs = ["marching_squares.h"],
    deps = ["@skia//:core"],
)

cc_test(
    name = "marching_squares_test",
    srcs = ["marching_squares_test.cc"],
    deps = [
        ":marching_squares",
        "@skia//:core",
    ],
)

cc_library(
    name = "shape_builder",
    srcs = ["shape_builder.cc"],
    hdrs = ["shape_builder.h"],
    deps = ["@skia//:core"],
)

cc_test(
    name = "shape_builder_test",
    srcs = ["shape_builder_test.cc"],
    deps = [
        ":shape_builder",
        "@skia//:core",
    ],
)
