load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "color_utils",
    srcs = ["color_utils.cc"],
    hdrs = ["color_utils.h"],
    deps = ["@skia//:core"],
)

cc_library(
    name = "random_permutation",
    srcs = ["random_permutation.cc"],
    hdrs = ["random_permutation.h"],
)

cc_test(
    name = "color_utils_test",
    srcs = ["color_utils_test.cc"],
    deps = [":color_utils"],
)

cc_test(
    name = "random_permutation_test",
    srcs = ["random_permutation_test.cc"],
    deps = [":random_permutation"],
)
