load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "fiddle_base",
    srcs = ["fiddle_base.cc"],
    hdrs = ["fiddle_base.h"],
)

cc_library(
    name = "fiddle_svg",
    srcs = ["fiddle_svg.cc"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":fiddle_base",
        "@skia//:core",
        "@skia//:svg_writer",
    ],
)

cc_test(
    name = "fiddle_base_test",
    srcs = ["fiddle_base_test.cc"],
    deps = [":fiddle_base"],
)

cc_library(
    name = "fiddle_registry",
    srcs = ["fiddle_registry.cc"],
    hdrs = ["fiddle_registry.h"],
    deps = [":fiddle_base"],
)

cc_library(
    name = "fiddle_manager",
    srcs = ["fiddle_manager.cc"],
    hdrs = ["fiddle_manager.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":fiddle_base",
        ":fiddle_registry",
        ":fiddle_svg",
        "//fiddles:contour_lines_fiddle",
        "//fiddles:elastic_text_fiddle",
        "//fiddles:envelope_distort_fiddle",
        "//fiddles:mesh_deform_fiddle",
        "//fiddles:ribbon_field_fiddle",
        "//fiddles:shape_intersection_fiddle",
        "//fiddles:shape_morphing_fiddle",
        "//fiddles:shape_tracing_fiddle",
        "//fiddles:skia_cpu_fiddle",
        "//fiddles:skia_webgl_fiddle",
        "//fiddles:sksl_image_proc_fiddle",
        "//fiddles:vortex_field_fiddle",
    ],
)
