load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "raster_canvas_context",
    srcs = ["raster_canvas_context.cc"],
    hdrs = ["raster_canvas_context.h"],
    deps = [
        "//core:fiddle_base",
        "@skia//:core",
    ],
)

cc_library(
    name = "webgl_canvas_context",
    srcs = ["webgl_canvas_context.cc"],
    hdrs = ["webgl_canvas_context.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//core:fiddle_base",
        "@skia//:core",
        "@skia//:ganesh_gl",
        "@skia//:ganesh_webgl_factory",
    ],
)
