load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "graphite_canvas_context",
    srcs = ["graphite_canvas_context.cc"],
    hdrs = ["graphite_canvas_context.h"],
    target_compatible_with = select({
        "//:wasm_build": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "@skia//:core",
        "@skia//:graphite_native_dawn",
    ],
)
